name: Build AED

env:
  tex_input_file: 'aed'
  pdfs_repository: 'https://github.com/rf-slf-4x1/cheatsheets-pdf'
  TOKEN: ${{secrets.TOKEN}}

on:
  push:
    paths: ['aed.tex', 'def.tex', 'aed_imgs/*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install latex
        run: |
          sudo apt-get update
          sudo apt-get install latexdiff texlive-latex-base texlive-science texlive-lang-cyrillic cm-super
      - name: Build PDF
        run: pdflatex -interaction=nonstopmode -shell-escape ${{env.tex_input_file}}.tex
      - name: Upload to work repo
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          target_branch: main
          commit_message: ${{ github.event.head_commit.message }}, work ${{env.tex_input_file}}
          files: ${{env.tex_input_file}}.pdf
          remote_repository: ${{env.pdfs_repository}}
          access_token: ${{env.TOKEN}}
          force: true
