name: Build AED

env:
  tex_input_file: 'aed'
  pdfs_repository: 'https://github.com/rf-slf-4x1/cheatsheets-pdf'
  TOKEN: ${{secrets.TOKEN}}

on:
  push:
    paths: ['aed.tex', 'def.tex', 'aed_imgs/*']

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install latex
        run: sudo apt-get install latexdiff texlive-latex-base
      - name: Prepare tex
        run:  cp ${{env.tex_input_file}}.tex ${{env.tex_input_file}}_new.tex
      - name: Prepare diff
        run: |
            git fetch origin main
            git diff HEAD~1 ${{env.tex_input_file}}.tex > diff.diff
      - name: Apply diff
        run:  git apply -R diff.diff
      - name: Run latexdiff
        run: latexdiff -t CTRADITIONAL ${{env.tex_input_file}}.tex ${{env.tex_input_file}}_new.tex > ${{env.tex_input_file}}_diff.tex
      - name: Build PDF
        run: pdflatex -interaction=nonstopmode -shell-escape ${{env.tex_input_file}}_new.tex
      - name: Build diff PDF
        run: pdflatex -interaction=nonstopmode -shell-escape ${{env.tex_input_file}}_diff.tex
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: ${{env.tex_input_file}}.pdf
          path: ${{env.tex_input_file}}_diff.pdf
        if: always()
      - name: Renaming pdf
        run: mv ${{env.tex_input_file}}_new.pdf ${{env.tex_input_file}}.pdf
      - name: Upload to work repo
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          target_branch: main
          commit_message: ${{ github.event.head_commit.message }}, work ${{env.tex_input_file}}
          files: ${{env.tex_input_file}}.pdf
          remote_repository: ${{env.pdfs_repository}}
          access_token: ${{env.TOKEN}}
          force: true
