name: Build example
on:
  push:
    paths: ['example.tex', 'def.tex']
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build PDFs
        uses: dante-ev/latex-action@latest
        with:
          root_file: example.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: example.pdf
          path: example.pdf
        if: always()
      - name: Upload to work repo
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          target_branch: main
          commit_message: ${{ github.event.head_commit.message }} example.pdf
          files: example.pdf
          remote_repository: https://github.com/rf-slf-4x1/cheatsheets-pdf
          access_token: ${{secrets.TOKEN}}
          force: true
