name: Build MOE

env:
  tex_input_file: 'moe'
  pdfs_repository: 'https://github.com/rf-slf-4x1/cheatsheets-pdf'
  TOKEN: ${{secrets.TOKEN}}

on:
  push:
    paths: ['moe.tex', 'def.tex']

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install latex
        run: sudo apt-get install latexdiff texlive-latex-base texlive-science texlive-lang-cyrillic cm-super
      - name: Prepare tex
        run:  cp ${{env.tex_input_file}}.tex ${{env.tex_input_file}}_new.tex
      - name: Prepare diff
        run: |
            git fetch origin main
            git diff HEAD^..HEAD ${{env.tex_input_file}}.tex > diff.diff
      - name: Apply diff
        run:  git apply -R diff.diff --allow-empty
    
  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Run latexdiff
        run: latexdiff -t CTRADITIONAL ${{env.tex_input_file}}.tex ${{env.tex_input_file}}_new.tex > ${{env.tex_input_file}}_diff.tex
      - name: Build PDF
        run: pdflatex -interaction=nonstopmode -shell-escape ${{env.tex_input_file}}_new.tex
      - name: Build diff PDF
        run: pdflatex -interaction=nonstopmode -shell-escape ${{env.tex_input_file}}_diff.tex
    
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Renaming pdf
        run: mv ${{env.tex_input_file}}_new.pdf ${{env.tex_input_file}}.pdf
      - name: Upload to work repo
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          target_branch: main
          commit_message: ${{ github.event.head_commit.message }}, work ${{env.tex_input_file}}
          files: ${{env.tex_input_file}}.pdf ${{env.tex_input_file}}_diff.pdf
          remote_repository: ${{env.pdfs_repository}}
          access_token: ${{env.TOKEN}}
          force: true
